account:
  server: localhost
  user: sa
  password: 756SAd
  account: FNLAccount
battle:
  server: localhost
  user: sa
  password: 756SAd
  battle: FNLBattle
billing:
  server: localhost
  user: sa
  password: 756SAd
  billing: FNLBilling
game:
  server: localhost
  user: sa
  password: 756SAd
  game: FNLGame2155
logs:
  server: localhost
  user: sa
  password: 756SAd
  logs: FNLLog
parm:
  server: localhost
  user: sa
  password: 756SAd
  parm: FNLParm
statistics:
  server: localhost
  user: sa
  password: 756SAd
  statistics: FNLStatistics